FROM quay.io/fedora/fedora-bootc:latest@sha256:a417faefe77fd874109d3408a2121e267f7cf67339c2b47a23ab3e22415fb770 AS bootc

FROM quay.io/fedora/fedora:latest@sha256:7312764716c9b6e205b1fbd394dea09c8b9ea5ebedb4ea53c868ddaebb9d4bc3

ENV USERNAME="ublue"

COPY --from=bootc --chmod=0755 /usr/libexec/bootc-base-imagectl /usr/libexec/bootc-base-imagectl
COPY --from=bootc /usr/share/doc/bootc-base-imagectl /usr/share/doc/

RUN --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    bash <<'RUNEOF'
set -eoux pipefail
dnf5 config-manager setopt install_weak_deps=False
dnf5 copr -y enable ublue-os/packages

dnf5 install -y \
    ShellCheck \
    cpp \
    erofs-utils \
    golang-oras \
    just \
    openssl \
    python3 \
    rpm-ostree \
    systemd-container \
    selinux-policy-targeted \
    sbsigntools \
    shfmt \
    socat \
    tmux \
    ublue-os-signing \
    yq \
    zstd

# syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/bin

# TODO: Determine if we can use latest cosign
# cosign
# while [[ -z "${COSIGN_VERSION:-}" ]]; do
#     COSIGN_VERSION=$(curl https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d : -f2 | tr -d "v\", ") || (sleep 30)
# done
# dnf5 install -y "https://github.com/sigstore/cosign/releases/latest/download/cosign-${COSIGN_VERSION}-1.$(rpm -E %_arch).rpm"
dnf5 install -y "https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-2.4.1-1.$(rpm -E %_arch).rpm"

# macadam
if [[ "$(rpm -E %_arch)" =~ x86_64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-amd64"
elif [[ "$(rpm -E %_arch)" =~ aarch64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-arm64"
else
    echo "Unsupported Arch" >&2
    exit 1
fi
chmod +x /usr/bin/macadam
macadam completion bash >/etc/bash_completion.d/macadam.sh

# bootc-base-imagectl
chmod +x /usr/libexec/bootc-base-imagectl

# Cleanup
dnf5 copr -y disable ublue-os/packages
dnf5 clean all
RUNEOF

LABEL \
    "name"="devcontainer" \
    "org.opencontainers.image.name"="devcontainer" \
    "org.opencontainers.image.url"="https://github.com/ublue-os/devcontainer" \
    "org.opencontainers.image.vendor"="Universal Blue" \
    "org.opencontainers.image.version"="base" \
    "vendor"="Universal Blue" \
    "version"="base"
